import { EXAMPLES } from './src/prism-core.mjs';

const $ = (id) => document.getElementById(id);
const input = $('cobolInput');
const summary = $('summary');
const javaOut = $('javaOut');
const irOut = $('irOut');
const sourceOut = $('sourceOut');
const cfgOut = $('cfgOut');
const gapsOut = $('gapsOut');
const manifestOut = $('manifestOut');
const artifactList = $('artifactList');
const exampleList = $('exampleList');
const statusLine = $('statusLine');
const tabs = [...document.querySelectorAll('[data-tab]')];
const panels = [...document.querySelectorAll('[data-panel]')];
let currentRun = null;
let examples = EXAMPLES;

function showTab(name) {
  tabs.forEach(t => t.classList.toggle('active', t.dataset.tab === name));
  panels.forEach(p => p.hidden = p.dataset.panel !== name);
}

tabs.forEach(t => t.addEventListener('click', () => showTab(t.dataset.tab)));

function renderExamples() {
  exampleList.innerHTML = examples.map((ex, index) => `
    <button class="example ${index === 0 ? 'selected' : ''}" data-example="${ex.id}">
      <strong>${ex.title}</strong><span>${ex.description}</span>
    </button>`).join('');
  exampleList.querySelectorAll('[data-example]').forEach(btn => btn.addEventListener('click', () => {
    const selected = examples.find(e => e.id === btn.dataset.example);
    if (!selected) return;
    input.value = selected.source;
    exampleList.querySelectorAll('.example').forEach(b => b.classList.toggle('selected', b === btn));
    translate();
  }));
}

async function loadExamples() {
  try {
    const response = await fetch('/api/examples');
    if (response.ok) examples = (await response.json()).examples;
  } catch (_) {
    // Local static fallback keeps the UI usable during file:// or simple http-server development.
  }
  renderExamples();
  input.value = examples[0].source;
}

async function translate() {
  statusLine.textContent = 'Running backend engine…';
  try {
    const response = await fetch('/api/translate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ source: input.value })
    });
    if (!response.ok) throw new Error(await response.text());
    currentRun = await response.json();
    renderRun(currentRun);
    statusLine.textContent = `Run ${currentRun.runId} generated by backend engine`;
  } catch (err) {
    statusLine.textContent = `Backend unavailable (${err.message}). Running local engine fallback for development only.`;
    const mod = await import('./src/prism-core.mjs');
    currentRun = mod.createRunArtifacts(input.value, { runId: 'local-preview' });
    renderRun(currentRun);
  }
}

function renderRun(result) {
  const gapErrors = result.gaps.filter(g => g.severity === 'error').length;
  const gapWarnings = result.gaps.filter(g => g.severity !== 'error').length;
  summary.innerHTML = `
    <div class="metric"><strong>${result.summary.programId}</strong><span>Program ID</span></div>
    <div class="metric"><strong>${result.runId}</strong><span>Run ID</span></div>
    <div class="metric"><strong>${result.summary.statements}</strong><span>Statements</span></div>
    <div class="metric"><strong>${result.summary.semanticOperations}</strong><span>Semantic ops</span></div>
    <div class="metric ${gapErrors ? 'bad' : gapWarnings ? 'warn' : 'good'}"><strong>${result.summary.gaps}</strong><span>Gaps</span></div>`;
  javaOut.textContent = result.java;
  irOut.textContent = JSON.stringify(result.semanticIr, null, 2);
  sourceOut.textContent = JSON.stringify({ sourceModel: result.sourceModel, symbols: result.symbols, readWrite: result.readWrite }, null, 2);
  cfgOut.textContent = JSON.stringify(result.cfg, null, 2);
  gapsOut.textContent = result.gaps.length ? JSON.stringify(result.gaps, null, 2) : '[]\n\nNo MVP gaps detected for supported constructs.';
  const manifestPath = Object.keys(result.artifacts).find(p => p.endsWith('/manifest.json'));
  manifestOut.textContent = JSON.stringify(result.artifacts[manifestPath], null, 2);
  artifactList.innerHTML = Object.keys(result.artifacts).sort().map(path => `<li><code>${path}</code></li>`).join('');
}

function download(filename, text, type = 'application/json') {
  const blob = new Blob([text], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

$('runBtn').addEventListener('click', translate);
$('copyJavaBtn').addEventListener('click', async () => navigator.clipboard.writeText(javaOut.textContent));
$('downloadBundleBtn').addEventListener('click', () => {
  if (!currentRun) return;
  download(`${currentRun.runId}-artifacts.json`, JSON.stringify(currentRun.artifacts, null, 2));
});
$('downloadJavaBtn').addEventListener('click', () => {
  if (!currentRun) return;
  download(`${currentRun.targetIr.className}.java`, currentRun.java, 'text/plain');
});
input.addEventListener('input', () => window.clearTimeout(window.__prismTimer) || (window.__prismTimer = window.setTimeout(translate, 500)));
showTab('java');
await loadExamples();
translate();
